#!/usr/bin/env bash
# Verify that our decorator metadata emit matches what NestJS dependency
# injection expects.
#
# NestJS resolves constructor dependencies by reading the design:paramtypes
# metadata tsc emits. If our compiler emits different metadata, DI silently
# resolves the wrong providers — the failure would surface as a runtime
# injection error in the user's app, not as a compile error here. So the
# baseline in tests/decorators/expected-di-metadata.txt was generated by real
# tsc, and this script asserts we still match it.
#
#   ./scripts/verify-decorator-emit.sh              check against the baseline
#   ./scripts/verify-decorator-emit.sh --regenerate rebuild it from real tsc
#
# The baseline covers class-typed params (live class references), interface and
# generic-alias params (Object), optional primitives (String), and the __param
# positions for @Inject/@Optional.
#
# Note: our full output is NOT byte-identical to tsc. tsgo preserves per-
# parameter comments in a multi-line parameter list where tsc collapses them,
# and our rewriter appends .js to relative imports. Neither changes semantics;
# only the metadata below is load-bearing, which is why this compares that
# rather than whole files.
set -euo pipefail

TSC_BASELINE_VERSION="5.9.3" # the version @nestjs/cli 11.x depends on
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
FIXTURE="$ROOT/tests/decorators"
BASELINE="$FIXTURE/expected-di-metadata.txt"

extract_metadata() {
  grep -h 'design:\|__param(' "$1" | grep -v '^ *//' | sed 's/^ *//'
}

if [ "${1:-}" = "--regenerate" ]; then
  echo "Regenerating baseline from tsc@$TSC_BASELINE_VERSION..."
  cd "$FIXTURE"
  npm install --no-save --silent "typescript@$TSC_BASELINE_VERSION"
  rm -rf tsc-dist
  ./node_modules/.bin/tsc -p tsconfig.json --outDir tsc-dist
  extract_metadata tsc-dist/service.js > "$BASELINE"
  rm -rf tsc-dist node_modules package-lock.json
  echo "Wrote $BASELINE"
  exit 0
fi

if [ ! -x "$ROOT/bin/ttsgo" ]; then
  echo "bin/ttsgo not found — run 'just build' first" >&2
  exit 1
fi

cd "$FIXTURE"
rm -rf dist
"$ROOT/bin/ttsgo" -p tsconfig.json >/dev/null

if ! diff -u "$BASELINE" <(extract_metadata dist/service.js); then
  echo >&2
  echo "Decorator metadata diverged from tsc@$TSC_BASELINE_VERSION." >&2
  echo "NestJS dependency injection reads exactly these values." >&2
  exit 1
fi

# The metadata is only meaningful if the output actually runs.
OUT=$(node dist/main.js)
EXPECTED="decorators ok: row true"
if [ "$OUT" != "$EXPECTED" ]; then
  echo "Unexpected runtime output:" >&2
  echo "  got:      $OUT" >&2
  echo "  expected: $EXPECTED" >&2
  exit 1
fi

rm -rf dist
echo "Decorator metadata matches tsc@$TSC_BASELINE_VERSION, and the output runs."
